### PR TITLE
Adventure compatibility

### PR DESCRIPTION
**Pull request by martinheidegger**
It would be great if we had to maintain only one beast, so I try to sum up all the things that workshopper would need to do to become adventure "compatible".

- [x] Allow an exercise to be [an EventDispatcher (current state)](https://github.com/rvagg/workshopper/blob/7a6604d9754dbbad906e7578a23a8c52ce352bce/workshopper.js#L312) or an object with run/verify function or simply a `function` (that gets the string "run" or "verify" property passed in)
- [x] Allow various properties to be just strings instead of file references (adventure.problem, etc.)
- [x] Make accesses to the file system optional: i.e. if the property "help" is given don't try to load the "helpFile" and make the helpFile optional (if given then empty)
- [x] Make the menu description optional and implement an `.add` method to setup the exercises. 
- [x] Process the result of an exercise in a compatible fashion to adventure

Probably some other tweaks needed too...

### CODE REVIEW

**Comment by timoxley** [comment]
This is looking great @martinheidegger. :heart_eyes_cat:

**Comment by martinheidegger** [comment]
@timoxley Well, it will work but it will also be slightly ugly. I will need to refactor/clean quite a bit.

**Comment by timoxley** [comment]
did you look at implementing workshopper API on top of adventure rather than paring workshopper back to be adventure-like?

**Comment by martinheidegger** [comment]
@timoxley No, it would need quite a few changes on adventure to get that done and I dread a discussion with substack.

**Comment by timoxley** [comment]
I've had commits merged on adventure, it's active. substack is very reasonable if you can capture his attention.

**Comment by martinheidegger** [comment]
Well, I havn't got endless time and this is almost done :)

**Comment by timoxley** [comment]
> "or an object with run/verify function or simply a function (that gets the string "run" or "verify" property passed in)"

I'm wondering if this variable types thing makes compatibility more complicated. If we just have one format, the others can be converted to/from.

**Comment by martinheidegger** [comment]
Most of the issues I am dealing with are legacy- and petty issues. i.e. in workshopper: the way the "fail" data is passed on is slightly different from the way adventure does it. Also workshopper allows listening to events of an exercise. The passing of meta-data is slightly different and things like that. I am really not sure which way is better in most cases so I offer the features "optionally" as good as possible.

**Comment by timoxley** [comment]
I guess we can start with optional and maybe move to breaking them out as modular

**Comment by martinheidegger** [comment]
The current structure leaves quite a few parts that can be broken out into own modules already and I do have quite a few ideas on how to clean up the code and as a result build a few other packages that deal with subparts of. I hope someone(me) will have time to do so at some point.

**Comment by martinheidegger** [comment]
I tried the current workshopper as drop-in replaces in javascripting and for the most parts it seems to work :dancer:  @sethvincent can you try it and see if there is an issue somewhere?

**Comment by finnp** [comment]
I think adventure-workshopper is not piping the verify function to stdout. See: https://github.com/finnp/test-anything/pull/9

**Comment by martinheidegger** [comment]
Linking: https://github.com/finnp/test-anything/pull/9#issuecomment-94351181

**Comment by timoxley** [comment]
:+1:

**Pull request closed without merging**
