### PR TITLE
Added Ukrainian translation

### PR DESCRIPTION
**Pull request by denysdovhan**
I translated workshopper on Ukrainian. Please, check my changes and add my language.

image

Add Ukrainian into other languages, please. I've already added Ukrainian into:

* English ...
* German ...
* French ...
* Russian configs.

### CODE REVIEW

**Comment by terry-s** [comment]
Everything is ok. I've reviewed it.

**Comment by tgfjt** [comment]
Thank you:)

**Comment by sudodoki** [comment]
Great work, thanks for stepping up & doing Ukrainian translation :smile_cat:

**Comment by denysdovhan** [comment]
Great! 
So, I'll translate other workshops, if I will have free time. Wait for my new commits, guys!

**Pull request merged**
